language: node_js
node_js:
  - '6.4.0'
  - '6.2.0'
  - '6.1.0'
services:
  - mongodb
before_script:
  - sleep 15
  - mongo user_auth_demo --eval 'db.addUser("travis", "test");'
before_script:
  - npm install
script: npm run test