language: node_js
node_js:
  - '6.5.0'
  - '6.4.0'
  - '6.2.0'
services:
  - mongodb
before_script:
  - sleep 15
  - mongo user_auth_demo --eval 'db.addUser("travis", "test");'
  - npm install
branches:
  only:
    - master
script: npm run test
notification:
  email:
    - willhanchen@gmail.com
  on_success: always