language: node_js
node_js:
- 7.0.0
- 6.5.0
- 6.4.0
services:
- mongodb
before_script:
- sleep 15
- mongo user_auth_demo --eval 'db.addUser("travis", "test");'
- cd server
- npm install
branches:
  only:
  - master
script: npm run test
notification:
  email:
  - willhanchen@gmail.com
  on_success: always
deploy:
  provider: heroku
  api_key:
    secure: "IkQOrhrTF9vt6nGihJwPiIRbR7H/bZFMwXi4njoEb6TCFdVusypeTnBe4hipnz0qXOmuxVFKNLkzdAxvk0XLe2uvQUhzfMxZucvt0x19GjZmDPg8Vo+poNMlJ8HmVEa3LiPkQGDSVqPYU7VUa+O3aMmdl+Wx7BNb1ex/i699EThFrhhO8GBaYQb8nDgx08OHEU3URw50YwIkxr2Wc0LXTq4/3vnaubMKAWP0R8UXm/WFnSjYl9XpYz1ArskJprNjp67og/G/libB0s2OMAiWVUMLLkKOYncIgnJ7Fih7EbzX5YrSJjsC/E03TO4ofBkg+kdjPjoWjPFpQFfzQhzQO1R31bRRXSOOUkYKC2291Eix9eGlOXP5B/09huxgKU9bEk02uFGj1GWx8oXGm14rFGIid9td3Q6WUPgUqeyxsflln/gA+ZXxmqmdApE2h7btMnM4sS4euePaPwwQM2yjxeCUoK+LoB5EL6sk7ockPd8oYCBh8FL6ZbdAqntIPQ8PYFf+0Evvxetnzpiy20ZoNNH6QDG65oloX2EOMm8PD/R56BHbYb2OGczODk4yhyNBJyyYSYYKbUDBaqv4QstC3eZaAtYOAOwsbygV0wkEWpRv+5JbyxCfajTOmo+nfkS7v11Kcs6mw3BQTtyI+dSvRZq1kFzivVxkccBQEyq0yms="
  app: "user-authentication-nodejs"
